# storage/prometheus.yml
services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "19090:9090"
    networks: 
      - default
    volumes:
      - prom-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--storage.tsdb.path=/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  prom-data:
  prom-targets:
