# collectors/cadvisor.yml
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "18081:8081"
    networks:
      - default
    command:
      - "--port=8081"
      - "--store_container_labels=true"
      - "--global_housekeeping_interval=1m0s"
      - "--storage_duration=10s"
      # These optimizations lower CPU utilization of CAdvisor significantly (source: https://dev.to/cloudx/taming-cadvisors-high-cpu-usage-1nm5)
      - "--housekeeping_interval=1s"
      - "--docker_only=true" # This can be modified depending on necessity
      - "--disable_metrics=percpu,sched,tcp,udp,disk"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true